
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 8090


#---------all other commented since its added to the main configuration file ---------------
spring:
  application:
    name: students  #name of the application

  config:
    import: optional:configserver::http://localhost:8888

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/students
#    username: postgres
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect